-- =============================================================================
-- 000197: Tag Taxonomy Rework + Individuals as Source Type
-- =============================================================================
-- Collapses 14+ tag kinds into a hard/soft model:
--   Hard (locked): language, audience_role, reserved, safety, county, city,
--                  structure, platform, verification
--   Soft (unlocked): topic
-- Adds source_type to organizations for Individual support.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. SCHEMA CHANGES
-- ---------------------------------------------------------------------------

-- Add locked flag to tag_kinds (hard vs soft distinction)
ALTER TABLE tag_kinds ADD COLUMN locked BOOLEAN NOT NULL DEFAULT false;

-- Add source_type to organizations (organization vs individual)
ALTER TABLE organizations ADD COLUMN source_type TEXT NOT NULL DEFAULT 'organization'
    CHECK (source_type IN ('organization', 'individual'));

-- ---------------------------------------------------------------------------
-- 2. TAG KINDS: create new, update existing, rename
-- ---------------------------------------------------------------------------

-- Rename provider_language → language (update existing tags first, then kind)
UPDATE tags SET kind = 'language' WHERE kind IN ('provider_language', 'service_language');
DELETE FROM tag_kinds WHERE slug IN ('provider_language', 'service_language');

-- Rename verification_source → verification
UPDATE tags SET kind = 'verification' WHERE kind = 'verification_source';
DELETE FROM tag_kinds WHERE slug = 'verification_source';

-- Upsert all 10 tag kinds (9 hard + 1 soft)
INSERT INTO tag_kinds (slug, display_name, description, allowed_resource_types, required, is_public, locked)
VALUES
    ('language', 'Language', 'Languages the source or post is available in', '{organization,post}', false, true, true),
    ('audience_role', 'Audience Role', 'Who this content is for — reader motivation or persona', '{post}', false, true, true),
    ('reserved', 'Reserved', 'System behavioral tags (urgent, recurring, closed, etc.)', '{post}', false, false, true),
    ('safety', 'Safety', 'Safety and accessibility badges for sources and posts', '{organization,post}', false, true, true),
    ('county', 'County', 'Minnesota counties served (service area)', '{organization,post}', false, true, true),
    ('city', 'City', 'Minnesota cities served (service area)', '{organization,post}', false, true, true),
    ('structure', 'Structure', 'How the source is organized (nonprofit, co-op, government, etc.)', '{organization}', false, false, true),
    ('platform', 'Platform', 'Where the source publishes content', '{organization}', false, false, true),
    ('verification', 'Verification', 'How the source has been verified', '{organization}', false, false, true),
    ('topic', 'Topic', 'Content topic (food, housing, health, etc.). AI-provided and admin-expandable.', '{organization,post}', false, true, false)
ON CONFLICT (slug) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    allowed_resource_types = EXCLUDED.allowed_resource_types,
    is_public = EXCLUDED.is_public,
    locked = EXCLUDED.locked;

-- ---------------------------------------------------------------------------
-- 3. SEED: Languages (55)
-- ---------------------------------------------------------------------------
INSERT INTO tags (kind, value, display_name) VALUES
    ('language', 'en', 'English'),
    ('language', 'es', 'Spanish'),
    ('language', 'hmn', 'Hmong'),
    ('language', 'so', 'Somali'),
    ('language', 'vi', 'Vietnamese'),
    ('language', 'zh', 'Chinese'),
    ('language', 'ar', 'Arabic'),
    ('language', 'fr', 'French'),
    ('language', 'ko', 'Korean'),
    ('language', 'ru', 'Russian'),
    ('language', 'tl', 'Tagalog / Filipino'),
    ('language', 'pt', 'Portuguese'),
    ('language', 'ht', 'Haitian Creole'),
    ('language', 'hi', 'Hindi'),
    ('language', 'de', 'German'),
    ('language', 'pl', 'Polish'),
    ('language', 'it', 'Italian'),
    ('language', 'ur', 'Urdu'),
    ('language', 'fa', 'Persian / Farsi'),
    ('language', 'te', 'Telugu'),
    ('language', 'ja', 'Japanese'),
    ('language', 'gu', 'Gujarati'),
    ('language', 'bn', 'Bengali'),
    ('language', 'ta', 'Tamil'),
    ('language', 'pa', 'Punjabi'),
    ('language', 'ml', 'Malayalam'),
    ('language', 'om', 'Oromo'),
    ('language', 'am', 'Amharic'),
    ('language', 'ti', 'Tigrinya'),
    ('language', 'km', 'Khmer / Cambodian'),
    ('language', 'lo', 'Lao'),
    ('language', 'ksw', 'Karen (Sgaw Karen)'),
    ('language', 'my', 'Burmese'),
    ('language', 'ne', 'Nepali'),
    ('language', 'sw', 'Swahili'),
    ('language', 'yo', 'Yoruba'),
    ('language', 'th', 'Thai'),
    ('language', 'mr', 'Marathi'),
    ('language', 'uk', 'Ukrainian'),
    ('language', 'ro', 'Romanian'),
    ('language', 'el', 'Greek'),
    ('language', 'tr', 'Turkish'),
    ('language', 'he', 'Hebrew'),
    ('language', 'ps', 'Pashto'),
    ('language', 'ms', 'Malay'),
    ('language', 'id', 'Indonesian'),
    ('language', 'sq', 'Albanian'),
    ('language', 'bs', 'Bosnian'),
    ('language', 'sr', 'Serbian'),
    ('language', 'hr', 'Croatian'),
    ('language', 'ku', 'Kurdish'),
    ('language', 'hy', 'Armenian'),
    ('language', 'ka', 'Georgian'),
    ('language', 'dak', 'Dakota'),
    ('language', 'oji', 'Ojibwe'),
    ('language', 'nv', 'Navajo')
ON CONFLICT (kind, value) DO UPDATE SET display_name = EXCLUDED.display_name;

-- ---------------------------------------------------------------------------
-- 4. SEED: Audience Roles (37)
-- ---------------------------------------------------------------------------
INSERT INTO tags (kind, value, display_name, description) VALUES
    -- Seeking & Navigating
    ('audience_role', 'seeker', 'Seeker', 'Looking for services, resources, or information'),
    ('audience_role', 'newcomer', 'Newcomer', 'Recently arrived, learning how things work here'),
    ('audience_role', 'navigator', 'Navigator', 'Helping others find resources (case worker, friend, relative)'),
    ('audience_role', 'system-learner', 'System Learner', 'Trying to understand U.S. systems (healthcare, schools, taxes, legal)'),
    -- Family & Caregiving
    ('audience_role', 'parent', 'Parent / Guardian', 'Raising children, looking for family activities and school info'),
    ('audience_role', 'expectant-parent', 'Expectant Parent', 'Pregnant or preparing to adopt, seeking prenatal and birth resources'),
    ('audience_role', 'caregiver', 'Elder / Family Caregiver', 'Caring for aging parents or family members with disabilities'),
    ('audience_role', 'youth', 'Young Person', 'Teen or young adult looking for opportunities, activities, mentorship'),
    ('audience_role', 'pet-owner', 'Pet / Animal Owner', 'Seeking vet care, pet food assistance, animal services'),
    -- Work & Money
    ('audience_role', 'job-seeker', 'Job Seeker', 'Looking for employment, training, or career development'),
    ('audience_role', 'worker', 'Worker', 'Employed, seeking labor rights info, workplace resources, professional dev'),
    ('audience_role', 'entrepreneur', 'Entrepreneur', 'Starting or growing a small business'),
    ('audience_role', 'investor', 'Local Investor / Funder', 'Looking to invest in or fund local businesses and projects'),
    ('audience_role', 'financial-seeker', 'Financial Seeker', 'Seeking grants, loans, financial literacy, or debt help'),
    ('audience_role', 'vendor', 'Vendor / Seller', 'Selling goods at markets, fairs, or online; looking for opportunities'),
    -- Giving & Doing
    ('audience_role', 'volunteer', 'Volunteer', 'Wants to give time and labor to community causes'),
    ('audience_role', 'donor', 'Donor', 'Wants to give money, goods, or food to people or organizations'),
    ('audience_role', 'mentor', 'Mentor', 'Wants to share knowledge, guide someone, or teach a skill'),
    ('audience_role', 'fixer', 'Fixer / Maker', 'Attends repair cafes, fix-it clinics, DIY workshops; shares hands-on skills'),
    ('audience_role', 'host', 'Host / Sharer', 'Offers space, rides, storage, tools, or other shared resources'),
    ('audience_role', 'foster-sponsor', 'Foster / Sponsor', 'Interested in fostering children/animals or sponsoring refugees'),
    -- Belonging & Connecting
    ('audience_role', 'neighbor', 'Neighbor', 'Wants to know what is happening nearby, stay connected'),
    ('audience_role', 'culture-keeper', 'Culture Keeper', 'Preserving language, traditions, food, music, or ceremonies'),
    ('audience_role', 'faith-member', 'Faith Community Member', 'Engaged in a religious or spiritual community'),
    ('audience_role', 'socializer', 'Socializer', 'Looking for events, gatherings, clubs, and ways to meet people'),
    ('audience_role', 'artist-creative', 'Artist / Creative', 'Seeking performance, exhibition, or collaboration opportunities'),
    ('audience_role', 'athlete', 'Athlete / Recreation Seeker', 'Looking for sports leagues, fitness programs, outdoor activities'),
    -- Health & Safety
    ('audience_role', 'health-seeker', 'Health Seeker', 'Looking for medical care, mental health support, or wellness'),
    ('audience_role', 'recovery', 'Person in Recovery', 'Seeking addiction recovery support, sober community, meetings'),
    ('audience_role', 'survivor', 'Survivor', 'Escaping DV, trafficking, or abuse; seeking safety'),
    ('audience_role', 'housing-seeker', 'Housing Seeker', 'Looking for affordable housing, shelter, or tenant rights'),
    -- Civic & Advocacy
    ('audience_role', 'civic-participant', 'Civic Participant', 'Wants to vote, attend hearings, serve on boards'),
    ('audience_role', 'advocate', 'Advocate / Organizer', 'Mobilizing around issues like housing, policing, environment'),
    ('audience_role', 'learner', 'Lifelong Learner', 'Taking classes, attending workshops, pursuing education'),
    ('audience_role', 'storyteller', 'Storyteller', 'Wants to share their story, write, photograph, or document')
ON CONFLICT (kind, value) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description;

-- Remove old audience_role values that are superseded
DELETE FROM tags WHERE kind = 'audience_role' AND value IN ('recipient', 'participant', 'customer');

-- ---------------------------------------------------------------------------
-- 5. SEED: Reserved Tags (8)
-- ---------------------------------------------------------------------------
INSERT INTO tags (kind, value, display_name, description) VALUES
    ('reserved', 'urgent', 'Urgent', 'Time-sensitive content requiring immediate attention'),
    ('reserved', 'recurring', 'Recurring', 'Content that repeats on a schedule'),
    ('reserved', 'closed', 'Closed', 'No longer active or accepting responses'),
    ('reserved', 'need', 'Need', 'Expresses a need or request'),
    ('reserved', 'aid', 'Aid', 'Offers assistance or support'),
    ('reserved', 'action', 'Action', 'Calls for action or participation'),
    ('reserved', 'person', 'Person', 'About or featuring a specific person'),
    ('reserved', 'business', 'Business', 'Related to a business or commercial activity')
ON CONFLICT (kind, value) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description;

-- ---------------------------------------------------------------------------
-- 6. SEED: Safety Tags (35)
-- ---------------------------------------------------------------------------
INSERT INTO tags (kind, value, display_name, description) VALUES
    -- Identity & Documentation
    ('safety', 'no-id-required', 'No ID Required', 'Services available without government-issued ID'),
    ('safety', 'no-ssn-required', 'No SSN Required', 'Does not require a Social Security Number'),
    ('safety', 'immigration-safe', 'Immigration Safe', 'Will not ask about or report immigration status'),
    ('safety', 'sensitive-location', 'Sensitive Location', 'Recognized location where ICE has agreed not to enforce'),
    ('safety', 'confidential', 'Confidential', 'Personal info kept private, not shared with other agencies'),
    ('safety', 'anonymous', 'Anonymous', 'Can participate without giving any name'),
    -- Cost
    ('safety', 'free', 'Free', 'No cost for services or participation'),
    ('safety', 'sliding-scale', 'Sliding Scale', 'Fees adjust based on income or ability to pay'),
    ('safety', 'accepts-insurance', 'Accepts Insurance', 'Takes health insurance including Medical Assistance / MinnesotaCare'),
    ('safety', 'no-insurance-needed', 'No Insurance Needed', 'Serves people regardless of insurance status'),
    ('safety', 'free-legal', 'Free Legal Help', 'Pro bono or free legal services available'),
    -- Access & Scheduling
    ('safety', 'walk-in-welcome', 'Walk-In Welcome', 'No appointment needed'),
    ('safety', 'appointment-available', 'Appointment Available', 'Can schedule a specific time'),
    ('safety', 'after-hours', 'After Hours / Evenings', 'Available outside standard 9-to-5'),
    ('safety', 'weekend-hours', 'Weekend Hours', 'Open on Saturdays or Sundays'),
    ('safety', 'virtual-available', 'Virtual / Remote', 'Services accessible by phone or video call'),
    ('safety', 'home-visit', 'Home Visits', 'Provider will come to your home'),
    -- Physical Accessibility
    ('safety', 'wheelchair-accessible', 'Wheelchair Accessible', 'Building and services accessible to wheelchair users'),
    ('safety', 'transit-accessible', 'Transit Accessible', 'Reachable by Metro Transit bus or light rail'),
    ('safety', 'parking-available', 'Free Parking', 'Free parking on-site or nearby'),
    -- Language & Communication
    ('safety', 'multilingual-staff', 'Multilingual Staff', 'Staff who speak community languages'),
    ('safety', 'interpreter-available', 'Interpreter Available', 'Professional interpretation services provided'),
    ('safety', 'plain-language', 'Plain Language', 'Materials in simple, clear language'),
    ('safety', 'asl-available', 'ASL Available', 'American Sign Language interpretation available'),
    -- Population Safety
    ('safety', 'child-friendly', 'Child-Friendly', 'Children welcome; may have childcare or kids activities'),
    ('safety', 'childcare-provided', 'Childcare Provided', 'Free childcare available during services or events'),
    ('safety', 'trauma-informed', 'Trauma-Informed', 'Staff trained in trauma-sensitive practices'),
    ('safety', 'lgbtq-affirming', 'LGBTQ+ Affirming', 'Explicitly welcoming and safe for LGBTQ+ individuals'),
    ('safety', 'youth-safe', 'Youth Safe', 'Appropriate and safe environment for minors'),
    ('safety', 'sober-space', 'Sober Space', 'Alcohol-free and drug-free environment'),
    ('safety', 'gender-separated', 'Gender-Separated Option', 'Offers women-only, men-only, or gender-specific programming'),
    ('safety', 'domestic-violence-safe', 'DV Safe', 'Trained in DV safety protocols; confidential location'),
    ('safety', 'senior-friendly', 'Senior Friendly', 'Accommodations and patience for elderly visitors'),
    ('safety', 'pet-friendly', 'Pet Friendly', 'Service animals and/or pets welcome'),
    ('safety', 'unhoused-welcome', 'Unhoused Welcome', 'No address required; welcoming to people without stable housing')
ON CONFLICT (kind, value) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description;

-- ---------------------------------------------------------------------------
-- 7. SEED: Counties (87 MN counties)
-- ---------------------------------------------------------------------------
INSERT INTO tags (kind, value, display_name) VALUES
    ('county', 'aitkin', 'Aitkin'),
    ('county', 'anoka', 'Anoka'),
    ('county', 'becker', 'Becker'),
    ('county', 'beltrami', 'Beltrami'),
    ('county', 'benton', 'Benton'),
    ('county', 'big-stone', 'Big Stone'),
    ('county', 'blue-earth', 'Blue Earth'),
    ('county', 'brown', 'Brown'),
    ('county', 'carlton', 'Carlton'),
    ('county', 'carver', 'Carver'),
    ('county', 'cass', 'Cass'),
    ('county', 'chippewa', 'Chippewa'),
    ('county', 'chisago', 'Chisago'),
    ('county', 'clay', 'Clay'),
    ('county', 'clearwater', 'Clearwater'),
    ('county', 'cook', 'Cook'),
    ('county', 'cottonwood', 'Cottonwood'),
    ('county', 'crow-wing', 'Crow Wing'),
    ('county', 'dakota', 'Dakota'),
    ('county', 'dodge', 'Dodge'),
    ('county', 'douglas', 'Douglas'),
    ('county', 'faribault', 'Faribault'),
    ('county', 'fillmore', 'Fillmore'),
    ('county', 'freeborn', 'Freeborn'),
    ('county', 'goodhue', 'Goodhue'),
    ('county', 'grant', 'Grant'),
    ('county', 'hennepin', 'Hennepin'),
    ('county', 'houston', 'Houston'),
    ('county', 'hubbard', 'Hubbard'),
    ('county', 'isanti', 'Isanti'),
    ('county', 'itasca', 'Itasca'),
    ('county', 'jackson', 'Jackson'),
    ('county', 'kanabec', 'Kanabec'),
    ('county', 'kandiyohi', 'Kandiyohi'),
    ('county', 'kittson', 'Kittson'),
    ('county', 'koochiching', 'Koochiching'),
    ('county', 'lac-qui-parle', 'Lac qui Parle'),
    ('county', 'lake', 'Lake'),
    ('county', 'lake-of-the-woods', 'Lake of the Woods'),
    ('county', 'le-sueur', 'Le Sueur'),
    ('county', 'lincoln', 'Lincoln'),
    ('county', 'lyon', 'Lyon'),
    ('county', 'mahnomen', 'Mahnomen'),
    ('county', 'marshall', 'Marshall'),
    ('county', 'martin', 'Martin'),
    ('county', 'mcleod', 'McLeod'),
    ('county', 'meeker', 'Meeker'),
    ('county', 'mille-lacs', 'Mille Lacs'),
    ('county', 'morrison', 'Morrison'),
    ('county', 'mower', 'Mower'),
    ('county', 'murray', 'Murray'),
    ('county', 'nicollet', 'Nicollet'),
    ('county', 'nobles', 'Nobles'),
    ('county', 'norman', 'Norman'),
    ('county', 'olmsted', 'Olmsted'),
    ('county', 'otter-tail', 'Otter Tail'),
    ('county', 'pennington', 'Pennington'),
    ('county', 'pine', 'Pine'),
    ('county', 'pipestone', 'Pipestone'),
    ('county', 'polk', 'Polk'),
    ('county', 'pope', 'Pope'),
    ('county', 'ramsey', 'Ramsey'),
    ('county', 'red-lake', 'Red Lake'),
    ('county', 'redwood', 'Redwood'),
    ('county', 'renville', 'Renville'),
    ('county', 'rice', 'Rice'),
    ('county', 'rock', 'Rock'),
    ('county', 'roseau', 'Roseau'),
    ('county', 'scott', 'Scott'),
    ('county', 'sherburne', 'Sherburne'),
    ('county', 'sibley', 'Sibley'),
    ('county', 'st-louis', 'St. Louis'),
    ('county', 'stearns', 'Stearns'),
    ('county', 'steele', 'Steele'),
    ('county', 'stevens', 'Stevens'),
    ('county', 'swift', 'Swift'),
    ('county', 'todd', 'Todd'),
    ('county', 'traverse', 'Traverse'),
    ('county', 'wabasha', 'Wabasha'),
    ('county', 'wadena', 'Wadena'),
    ('county', 'waseca', 'Waseca'),
    ('county', 'washington', 'Washington'),
    ('county', 'watonwan', 'Watonwan'),
    ('county', 'wilkin', 'Wilkin'),
    ('county', 'winona', 'Winona'),
    ('county', 'wright', 'Wright'),
    ('county', 'yellow-medicine', 'Yellow Medicine')
ON CONFLICT (kind, value) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 8. SEED: Cities (~230 MN cities + Statewide)
-- ---------------------------------------------------------------------------
INSERT INTO tags (kind, value, display_name) VALUES
    ('city', 'statewide', 'Statewide'),
    ('city', 'ada', 'Ada'),
    ('city', 'adrian', 'Adrian'),
    ('city', 'aitkin', 'Aitkin'),
    ('city', 'albert-lea', 'Albert Lea'),
    ('city', 'alexandria', 'Alexandria'),
    ('city', 'andover', 'Andover'),
    ('city', 'anoka', 'Anoka'),
    ('city', 'apple-valley', 'Apple Valley'),
    ('city', 'appleton', 'Appleton'),
    ('city', 'argyle', 'Argyle'),
    ('city', 'arlington', 'Arlington'),
    ('city', 'ashby', 'Ashby'),
    ('city', 'austin', 'Austin'),
    ('city', 'bagley', 'Bagley'),
    ('city', 'baudette', 'Baudette'),
    ('city', 'baxter', 'Baxter'),
    ('city', 'bemidji', 'Bemidji'),
    ('city', 'benson', 'Benson'),
    ('city', 'big-lake', 'Big Lake'),
    ('city', 'bigfork', 'Bigfork'),
    ('city', 'bird-island', 'Bird Island'),
    ('city', 'blackduck', 'Blackduck'),
    ('city', 'blaine', 'Blaine'),
    ('city', 'blooming-prairie', 'Blooming Prairie'),
    ('city', 'bloomington', 'Bloomington'),
    ('city', 'blue-earth', 'Blue Earth'),
    ('city', 'brainerd', 'Brainerd'),
    ('city', 'brandon', 'Brandon'),
    ('city', 'breckenridge', 'Breckenridge'),
    ('city', 'brooklyn-center', 'Brooklyn Center'),
    ('city', 'brooklyn-park', 'Brooklyn Park'),
    ('city', 'brooks', 'Brooks'),
    ('city', 'browns-valley', 'Browns Valley'),
    ('city', 'brownsdale', 'Brownsdale'),
    ('city', 'buffalo', 'Buffalo'),
    ('city', 'burnsville', 'Burnsville'),
    ('city', 'byron', 'Byron'),
    ('city', 'caledonia', 'Caledonia'),
    ('city', 'cambridge', 'Cambridge'),
    ('city', 'canby', 'Canby'),
    ('city', 'cannon-falls', 'Cannon Falls'),
    ('city', 'carlton', 'Carlton'),
    ('city', 'chanhassen', 'Chanhassen'),
    ('city', 'chaska', 'Chaska'),
    ('city', 'chatfield', 'Chatfield'),
    ('city', 'chisago-city', 'Chisago City'),
    ('city', 'clara-city', 'Clara City'),
    ('city', 'clearbrook', 'Clearbrook'),
    ('city', 'cloquet', 'Cloquet'),
    ('city', 'cold-spring', 'Cold Spring'),
    ('city', 'coon-rapids', 'Coon Rapids'),
    ('city', 'cottage-grove', 'Cottage Grove'),
    ('city', 'cottonwood', 'Cottonwood'),
    ('city', 'crookston', 'Crookston'),
    ('city', 'crosby', 'Crosby'),
    ('city', 'crystal', 'Crystal'),
    ('city', 'currie', 'Currie'),
    ('city', 'dassel', 'Dassel'),
    ('city', 'dawson', 'Dawson'),
    ('city', 'delano', 'Delano'),
    ('city', 'detroit-lakes', 'Detroit Lakes'),
    ('city', 'dilworth', 'Dilworth'),
    ('city', 'dodge-center', 'Dodge Center'),
    ('city', 'duluth', 'Duluth'),
    ('city', 'eagan', 'Eagan'),
    ('city', 'eagle-lake', 'Eagle Lake'),
    ('city', 'east-bethel', 'East Bethel'),
    ('city', 'east-grand-forks', 'East Grand Forks'),
    ('city', 'eden-prairie', 'Eden Prairie'),
    ('city', 'edina', 'Edina'),
    ('city', 'elbow-lake', 'Elbow Lake'),
    ('city', 'elk-river', 'Elk River'),
    ('city', 'eveleth', 'Eveleth'),
    ('city', 'fairmont', 'Fairmont'),
    ('city', 'faribault', 'Faribault'),
    ('city', 'farmington', 'Farmington'),
    ('city', 'fergus-falls', 'Fergus Falls'),
    ('city', 'foley', 'Foley'),
    ('city', 'forest-lake', 'Forest Lake'),
    ('city', 'foxhome', 'Foxhome'),
    ('city', 'frazee', 'Frazee'),
    ('city', 'freeborn', 'Freeborn'),
    ('city', 'fridley', 'Fridley'),
    ('city', 'gaylord', 'Gaylord'),
    ('city', 'glencoe', 'Glencoe'),
    ('city', 'glenwood', 'Glenwood'),
    ('city', 'golden-valley', 'Golden Valley'),
    ('city', 'graceville', 'Graceville'),
    ('city', 'grand-marais', 'Grand Marais'),
    ('city', 'grand-rapids', 'Grand Rapids'),
    ('city', 'granite-falls', 'Granite Falls'),
    ('city', 'hallock', 'Hallock'),
    ('city', 'halstad', 'Halstad'),
    ('city', 'ham-lake', 'Ham Lake'),
    ('city', 'hancock', 'Hancock'),
    ('city', 'hastings', 'Hastings'),
    ('city', 'hendricks', 'Hendricks'),
    ('city', 'heron-lake', 'Heron Lake'),
    ('city', 'hibbing', 'Hibbing'),
    ('city', 'hills', 'Hills'),
    ('city', 'hinckley', 'Hinckley'),
    ('city', 'hopkins', 'Hopkins'),
    ('city', 'houston', 'Houston'),
    ('city', 'hugo', 'Hugo'),
    ('city', 'hutchinson', 'Hutchinson'),
    ('city', 'international-falls', 'International Falls'),
    ('city', 'inver-grove-heights', 'Inver Grove Heights'),
    ('city', 'isanti', 'Isanti'),
    ('city', 'ivanhoe', 'Ivanhoe'),
    ('city', 'jackson', 'Jackson'),
    ('city', 'janesville', 'Janesville'),
    ('city', 'jasper', 'Jasper'),
    ('city', 'jordan', 'Jordan'),
    ('city', 'karlstad', 'Karlstad'),
    ('city', 'kasson', 'Kasson'),
    ('city', 'lake-city', 'Lake City'),
    ('city', 'lakeville', 'Lakeville'),
    ('city', 'le-center', 'Le Center'),
    ('city', 'le-sueur', 'Le Sueur'),
    ('city', 'lewiston', 'Lewiston'),
    ('city', 'lindstrom', 'Lindstrom'),
    ('city', 'lino-lakes', 'Lino Lakes'),
    ('city', 'litchfield', 'Litchfield'),
    ('city', 'little-falls', 'Little Falls'),
    ('city', 'littlefork', 'Littlefork'),
    ('city', 'long-prairie', 'Long Prairie'),
    ('city', 'luverne', 'Luverne'),
    ('city', 'madelia', 'Madelia'),
    ('city', 'madison', 'Madison'),
    ('city', 'mahnomen', 'Mahnomen'),
    ('city', 'mankato', 'Mankato'),
    ('city', 'maple-grove', 'Maple Grove'),
    ('city', 'maplewood', 'Maplewood'),
    ('city', 'marshall', 'Marshall'),
    ('city', 'mcgregor', 'McGregor'),
    ('city', 'milaca', 'Milaca'),
    ('city', 'minneapolis', 'Minneapolis'),
    ('city', 'minnetonka', 'Minnetonka'),
    ('city', 'monticello', 'Monticello'),
    ('city', 'montevideo', 'Montevideo'),
    ('city', 'moorhead', 'Moorhead'),
    ('city', 'mora', 'Mora'),
    ('city', 'morris', 'Morris'),
    ('city', 'mounds-view', 'Mounds View'),
    ('city', 'mountain-lake', 'Mountain Lake'),
    ('city', 'nevis', 'Nevis'),
    ('city', 'new-brighton', 'New Brighton'),
    ('city', 'new-hope', 'New Hope'),
    ('city', 'new-ulm', 'New Ulm'),
    ('city', 'north-branch', 'North Branch'),
    ('city', 'north-mankato', 'North Mankato'),
    ('city', 'north-st-paul', 'North St. Paul'),
    ('city', 'northfield', 'Northfield'),
    ('city', 'oakdale', 'Oakdale'),
    ('city', 'ogilvie', 'Ogilvie'),
    ('city', 'olivia', 'Olivia'),
    ('city', 'ortonville', 'Ortonville'),
    ('city', 'otsego', 'Otsego'),
    ('city', 'owatonna', 'Owatonna'),
    ('city', 'park-rapids', 'Park Rapids'),
    ('city', 'perham', 'Perham'),
    ('city', 'pierz', 'Pierz'),
    ('city', 'pine-city', 'Pine City'),
    ('city', 'pine-river', 'Pine River'),
    ('city', 'pipestone', 'Pipestone'),
    ('city', 'plymouth', 'Plymouth'),
    ('city', 'preston', 'Preston'),
    ('city', 'princeton', 'Princeton'),
    ('city', 'prior-lake', 'Prior Lake'),
    ('city', 'ramsey', 'Ramsey'),
    ('city', 'red-lake-falls', 'Red Lake Falls'),
    ('city', 'red-wing', 'Red Wing'),
    ('city', 'redwood-falls', 'Redwood Falls'),
    ('city', 'richfield', 'Richfield'),
    ('city', 'robbinsdale', 'Robbinsdale'),
    ('city', 'rochester', 'Rochester'),
    ('city', 'roseau', 'Roseau'),
    ('city', 'rosemount', 'Rosemount'),
    ('city', 'roseville', 'Roseville'),
    ('city', 'sandstone', 'Sandstone'),
    ('city', 'sartell', 'Sartell'),
    ('city', 'sauk-rapids', 'Sauk Rapids'),
    ('city', 'savage', 'Savage'),
    ('city', 'shakopee', 'Shakopee'),
    ('city', 'shoreview', 'Shoreview'),
    ('city', 'silver-bay', 'Silver Bay'),
    ('city', 'slayton', 'Slayton'),
    ('city', 'sleepy-eye', 'Sleepy Eye'),
    ('city', 'south-st-paul', 'South St. Paul'),
    ('city', 'spicer', 'Spicer'),
    ('city', 'st-cloud', 'St. Cloud'),
    ('city', 'st-hilaire', 'St. Hilaire'),
    ('city', 'st-james', 'St. James'),
    ('city', 'st-louis-park', 'St. Louis Park'),
    ('city', 'st-michael', 'St. Michael'),
    ('city', 'st-paul', 'St. Paul'),
    ('city', 'st-peter', 'St. Peter'),
    ('city', 'staples', 'Staples'),
    ('city', 'starbuck', 'Starbuck'),
    ('city', 'stillwater', 'Stillwater'),
    ('city', 'thief-river-falls', 'Thief River Falls'),
    ('city', 'tofte', 'Tofte'),
    ('city', 'trimont', 'Trimont'),
    ('city', 'two-harbors', 'Two Harbors'),
    ('city', 'verndale', 'Verndale'),
    ('city', 'virginia', 'Virginia'),
    ('city', 'wabasha', 'Wabasha'),
    ('city', 'wabasso', 'Wabasso'),
    ('city', 'waconia', 'Waconia'),
    ('city', 'wadena', 'Wadena'),
    ('city', 'waite-park', 'Waite Park'),
    ('city', 'walker', 'Walker'),
    ('city', 'warren', 'Warren'),
    ('city', 'warroad', 'Warroad'),
    ('city', 'waseca', 'Waseca'),
    ('city', 'waubun', 'Waubun'),
    ('city', 'wells', 'Wells'),
    ('city', 'west-st-paul', 'West St. Paul'),
    ('city', 'wheaton', 'Wheaton'),
    ('city', 'white-bear-lake', 'White Bear Lake'),
    ('city', 'williams', 'Williams'),
    ('city', 'willmar', 'Willmar'),
    ('city', 'windom', 'Windom'),
    ('city', 'winona', 'Winona'),
    ('city', 'woodbury', 'Woodbury'),
    ('city', 'worthington', 'Worthington'),
    ('city', 'zimmerman', 'Zimmerman'),
    ('city', 'zumbrota', 'Zumbrota')
ON CONFLICT (kind, value) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 9. SEED: Structure Types (70)
-- ---------------------------------------------------------------------------
INSERT INTO tags (kind, value, display_name, description) VALUES
    -- Organization types (53)
    ('structure', 'nonprofit-501c3', '501(c)(3) Nonprofit', 'Tax-exempt charitable organization'),
    ('structure', 'nonprofit-501c4', '501(c)(4) Civic League', 'Social welfare org, may do lobbying'),
    ('structure', 'nonprofit-501c6', '501(c)(6) Trade Association', 'Business league, chamber, or trade board'),
    ('structure', 'nonprofit-fiscal-sponsor', 'Fiscally Sponsored Project', 'Operating under another org''s tax-exempt status'),
    ('structure', 'for-profit', 'For-Profit Business', 'Standard commercial business entity'),
    ('structure', 'b-corp', 'B Corporation', 'Certified benefit corporation'),
    ('structure', 'co-op', 'Cooperative', 'Member-owned and democratically governed'),
    ('structure', 'social-enterprise', 'Social Enterprise', 'Revenue-generating with a social mission'),
    ('structure', 'mutual-aid', 'Mutual Aid Network', 'Grassroots reciprocal support, no formal hierarchy'),
    ('structure', 'faith-based', 'Faith-Based Organization', 'Church, mosque, temple, synagogue, or faith-rooted ministry'),
    ('structure', 'interfaith-coalition', 'Interfaith Coalition', 'Cross-faith collaborative group'),
    ('structure', 'government-federal', 'Federal Agency', 'U.S. federal government office or program'),
    ('structure', 'government-state', 'State Agency', 'Minnesota state government office or program'),
    ('structure', 'government-county', 'County Agency', 'County government office'),
    ('structure', 'government-city', 'City Agency', 'Municipal office'),
    ('structure', 'government-tribal', 'Tribal Government', 'Sovereign tribal nation government or program'),
    ('structure', 'school-district', 'School District', 'Public school district office or program'),
    ('structure', 'public-library', 'Public Library', 'County or city library system'),
    ('structure', 'public-housing', 'Public Housing Authority', 'Government housing agency'),
    ('structure', 'quasi-governmental', 'Quasi-Governmental', 'Public-private hybrid (port authority, transit, etc.)'),
    ('structure', 'union', 'Labor Union', 'Workers'' union or labor council'),
    ('structure', 'professional-association', 'Professional Association', 'Association for practitioners in a field'),
    ('structure', 'chamber-of-commerce', 'Chamber of Commerce', 'Local business membership organization'),
    ('structure', 'business-improvement-district', 'Business Improvement District', 'Geographically defined business collective'),
    ('structure', 'community-development-corp', 'Community Development Corp', 'CDC focused on neighborhood economic development'),
    ('structure', 'community-land-trust', 'Community Land Trust', 'Nonprofit holding land for community benefit'),
    ('structure', 'foundation', 'Foundation', 'Grantmaking or endowed charitable foundation'),
    ('structure', 'community-foundation', 'Community Foundation', 'Place-based foundation pooling local donor funds'),
    ('structure', 'diaspora-association', 'Diaspora / Hometown Association', 'Group organized around shared country/region of origin'),
    ('structure', 'cultural-association', 'Cultural Association', 'Organization preserving and promoting a specific culture'),
    ('structure', 'clan-or-kinship-network', 'Clan or Kinship Network', 'Extended family or clan-based support structure'),
    ('structure', 'neighborhood-association', 'Neighborhood Association', 'Geographically defined resident group'),
    ('structure', 'block-club', 'Block Club', 'Hyper-local resident group for a block or small area'),
    ('structure', 'tenant-association', 'Tenant Association', 'Resident group in a building or housing complex'),
    ('structure', 'parent-teacher-org', 'Parent-Teacher Organization', 'School-based parent and teacher group'),
    ('structure', 'youth-group', 'Youth Group', 'Youth-led or youth-serving organized group'),
    ('structure', 'elder-circle', 'Elder Circle', 'Group organized around elder leadership or care'),
    ('structure', 'womens-group', 'Women''s Group', 'Group organized around women''s needs or leadership'),
    ('structure', 'mens-group', 'Men''s Group', 'Group organized around men''s needs or development'),
    ('structure', 'lgbtq-org', 'LGBTQ+ Organization', 'Group serving LGBTQ+ community members'),
    ('structure', 'veterans-org', 'Veterans Organization', 'Group serving military veterans and families'),
    ('structure', 'athletic-league', 'Athletic League or Club', 'Sports league, running club, or rec group'),
    ('structure', 'arts-collective', 'Arts Collective', 'Group of artists working collaboratively'),
    ('structure', 'media-outlet', 'Media Outlet', 'Newspaper, radio station, podcast, or news org'),
    ('structure', 'community-radio', 'Community Radio', 'Locally operated radio station'),
    ('structure', 'incubator-accelerator', 'Incubator / Accelerator', 'Program supporting new businesses or social ventures'),
    ('structure', 'informal-collective', 'Informal Collective', 'Unincorporated group with shared purpose'),
    ('structure', 'online-community', 'Online Community', 'Group existing primarily on a digital platform'),
    ('structure', 'health-clinic', 'Health Clinic', 'Medical or dental clinic serving community'),
    ('structure', 'food-shelf', 'Food Shelf / Pantry', 'Organization distributing free food'),
    ('structure', 'shelter', 'Shelter', 'Emergency or transitional housing provider'),
    ('structure', 'resettlement-agency', 'Resettlement Agency', 'Org helping refugees resettle'),
    ('structure', 'legal-aid', 'Legal Aid Organization', 'Free or low-cost legal services provider'),
    -- Individual types (17)
    ('structure', 'individual-organizer', 'Community Organizer', 'Person who mobilizes people around shared issues'),
    ('structure', 'individual-advocate', 'Advocate / Activist', 'Person publicly championing a cause'),
    ('structure', 'individual-practitioner', 'Licensed Practitioner', 'Doctor, lawyer, therapist, social worker, etc.'),
    ('structure', 'individual-healer', 'Traditional Healer', 'Herbalist, spiritual healer, traditional medicine'),
    ('structure', 'individual-educator', 'Educator / Tutor', 'Teacher, professor, or educational mentor'),
    ('structure', 'individual-artist', 'Artist / Performer', 'Musician, visual artist, poet, dancer, storyteller'),
    ('structure', 'individual-journalist', 'Journalist / Blogger', 'Independent reporter or content creator'),
    ('structure', 'individual-elected-official', 'Elected Official', 'City council, state legislator, school board'),
    ('structure', 'individual-business-owner', 'Small Business Owner', 'Sole proprietor or small shop owner'),
    ('structure', 'individual-vendor', 'Street Vendor / Market Seller', 'Selling goods at markets, fairs, or on the street'),
    ('structure', 'individual-tradesperson', 'Tradesperson', 'Electrician, plumber, mechanic, seamstress, etc.'),
    ('structure', 'individual-caregiver', 'Caregiver', 'Providing elder care, child care, or disability support'),
    ('structure', 'individual-religious-leader', 'Religious Leader', 'Pastor, imam, monk, elder, or spiritual director'),
    ('structure', 'individual-cultural-navigator', 'Cultural Navigator', 'Bridges cultures, helps newcomers navigate systems'),
    ('structure', 'individual-doula', 'Doula / Birth Worker', 'Pregnancy, birth, or postpartum support'),
    ('structure', 'individual-coach', 'Coach / Mentor', 'Life coach, career mentor, or sports coach'),
    ('structure', 'individual-volunteer-leader', 'Volunteer Leader', 'Person who coordinates volunteer efforts informally')
ON CONFLICT (kind, value) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description;

-- ---------------------------------------------------------------------------
-- 10. SEED: Platform Types (46)
-- ---------------------------------------------------------------------------
INSERT INTO tags (kind, value, display_name, description) VALUES
    ('platform', 'website', 'Website', 'Standalone website or blog'),
    ('platform', 'substack', 'Substack', 'Newsletter via Substack'),
    ('platform', 'medium', 'Medium', 'Articles on Medium'),
    ('platform', 'newsletter-email', 'Email Newsletter', 'Mailchimp, Constant Contact, etc.'),
    ('platform', 'podcast', 'Podcast', 'Apple Podcasts, Spotify, etc.'),
    ('platform', 'instagram', 'Instagram', 'Posts, stories, reels'),
    ('platform', 'facebook', 'Facebook', 'Facebook page or profile'),
    ('platform', 'facebook-group', 'Facebook Group', 'Facebook Group specifically'),
    ('platform', 'threads', 'Threads', 'Meta''s Threads platform'),
    ('platform', 'x', 'X (Twitter)', 'Posts on X / Twitter'),
    ('platform', 'bluesky', 'Bluesky', 'Posts on Bluesky'),
    ('platform', 'tiktok', 'TikTok', 'Short-form video'),
    ('platform', 'youtube', 'YouTube', 'Video content'),
    ('platform', 'linkedin', 'LinkedIn', 'Professional network'),
    ('platform', 'nextdoor', 'Nextdoor', 'Neighborhood-based social network'),
    ('platform', 'whatsapp', 'WhatsApp', 'WhatsApp groups or broadcast lists'),
    ('platform', 'whatsapp-channel', 'WhatsApp Channel', 'One-way broadcast channel'),
    ('platform', 'telegram', 'Telegram', 'Telegram groups or channels'),
    ('platform', 'signal', 'Signal', 'Signal groups for secure messaging'),
    ('platform', 'discord', 'Discord', 'Discord server or channel'),
    ('platform', 'reddit', 'Reddit', 'Subreddit or Reddit posts'),
    ('platform', 'eventbrite', 'Eventbrite', 'Event listings'),
    ('platform', 'meetup', 'Meetup', 'Group and event listings'),
    ('platform', 'gofundme', 'GoFundMe', 'Fundraising campaigns'),
    ('platform', 'givebutter', 'Givebutter', 'Fundraising and ticketing'),
    ('platform', 'google-business', 'Google Business Profile', 'Business listing on Google'),
    ('platform', 'yelp', 'Yelp', 'Business listing and reviews'),
    ('platform', 'patch', 'Patch', 'Local news and events'),
    ('platform', 'linktree', 'Linktree', 'Link aggregator page'),
    ('platform', 'google-forms', 'Google Forms', 'Intake, RSVP, or survey forms'),
    ('platform', 'calendly', 'Calendly', 'Appointment scheduling'),
    ('platform', 'square', 'Square Online', 'Storefront or appointments'),
    ('platform', 'etsy', 'Etsy', 'Handmade or vintage goods shop'),
    ('platform', 'shopify', 'Shopify', 'Online store'),
    ('platform', 'venmo', 'Venmo', 'Payment collection'),
    ('platform', 'cashapp', 'Cash App', 'Payment collection'),
    ('platform', 'patreon', 'Patreon', 'Membership and patronage'),
    ('platform', 'kickstarter', 'Kickstarter', 'Crowdfunding campaigns'),
    ('platform', 'caring-bridge', 'CaringBridge', 'Health journey updates'),
    ('platform', 'print-flyer', 'Print Flyer / Poster', 'Physical printed materials'),
    ('platform', 'community-bulletin', 'Community Bulletin Board', 'Physical or digital community board'),
    ('platform', 'radio', 'Radio', 'Local or community radio'),
    ('platform', 'public-access-tv', 'Public Access TV', 'Local public access television'),
    ('platform', 'sms-text', 'SMS / Text Blast', 'Information via text message'),
    ('platform', 'spotify', 'Spotify', 'Music or podcast content'),
    ('platform', 'soundcloud', 'SoundCloud', 'Audio content')
ON CONFLICT (kind, value) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description;

-- ---------------------------------------------------------------------------
-- 11. SEED: Verification (5)
-- ---------------------------------------------------------------------------
INSERT INTO tags (kind, value, display_name, description) VALUES
    ('verification', 'admin-verified', 'Admin Verified', 'Verified by the admin team'),
    ('verification', 'community-vouched', 'Community Vouched', 'Vouched for by community members'),
    ('verification', 'self-reported', 'Self-Reported', 'Information provided by the source itself'),
    ('verification', 'partner-verified', 'Partner Verified', 'Verified through a partner organization'),
    ('verification', 'government-registered', 'Government Registered', 'Registered with government (501c3, state filing, etc.)')
ON CONFLICT (kind, value) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description;

-- ---------------------------------------------------------------------------
-- 12. DEPRECATE: Remove old tag_kinds (tags and taggables left intact)
-- ---------------------------------------------------------------------------
DELETE FROM tag_kinds WHERE slug IN (
    'post_type',
    'population',
    'community_served',
    'service_offered',
    'org_leadership',
    'business_model',
    'certification',
    'ownership',
    'worker_structure',
    'listing_type',
    'provider_category',
    'provider_specialty',
    'with_agent',
    'service_area'
);
